kind: ImageStreamList
apiVersion: v1
metadata:
  name: kogito-image-streams
  annotations:
    description: ImageStream definitions for Kogito images
    openshift.io/provider-display-name: Kie Group.
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-runtime-native
      annotations:
        openshift.io/display-name: Runtime image for Kogito based on Quarkus native image
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for Kogito based on Quarkus native image
            iconClass: icon-jbpm
            tags: runtime,kogito,quarkus
            supports: quarkus
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-runtime-native:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-runtime-jvm
      annotations:
        openshift.io/display-name: Runtime image for Kogito based on Quarkus or Springboot JVM image
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for Kogito based on Quarkus or Springboot JVM image
            iconClass: icon-jbpm
            tags: runtime,kogito,quarkus,springboot,jvm
            supports: quarkus
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-runtime-jvm:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-builder
      annotations:
        openshift.io/display-name: Platform for building Kogito based on Quarkus or Springboot
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Platform for building Kogito based on Quarkus or Springboot
            iconClass: icon-jbpm
            tags: builder,kogito,quarkus,springboot
            supports: quarkus
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-builder:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-data-index-infinispan
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Data Index Service for Infinispan persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Data Index Service with Infinispan
            iconClass: icon-jbpm
            tags: kogito,data-index,data-index-infinispan
            supports: persistence backed by Infinispan server
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-data-index-infinispan:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-data-index-mongodb
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Data Index Service for MongoDB persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Data Index Service with Mongodb
            iconClass: icon-jbpm
            tags: kogito,data-index,data-index-mongodb
            supports: persistence backed by Mongodb server
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-data-index-mongodb:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-trusty-infinispan
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Trusty Service for Infinispan persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Trusty Service with Infinispan
            iconClass: icon-jbpm
            tags: kogito,trusty,trusty-infinispan
            supports: persistence backed by Infinispan server
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-trusty-infinispan:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-trusty-redis
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Trusty Service for Redis persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Trusty Service with Redis
            iconClass: icon-jbpm
            tags: kogito,trusty,trusty-redis
            supports: persistence backed by Redis server
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-trusty-redis:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-trusty-ui
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Trusty UI Service
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Trusty UI Service
            iconClass: icon-jbpm
            tags: kogito,trusty-ui
            supports: Audit UI
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-trusty-ui:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jit-runner
      annotations:
        openshift.io/display-name: Runtime image for the Kogito JIT Runner
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito JIT Runner
            iconClass: icon-jbpm
            tags: kogito,jit-runner
            supports: JIT Runner
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jit-runner:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-explainability
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Explainability Service
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Explainability Service
            iconClass: icon-jbpm
            tags: kogito,explainability
            supports: explainability for decisions
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-explainability:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jobs-service
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Jobs Service
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Jobs Service
            iconClass: icon-jbpm
            tags: kogito,jobs-service
            supports: out-of-box process timers
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jobs-service:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-management-console
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Management Console
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Management Console
            iconClass: icon-jbpm
            tags: kogito,management-console
            supports: business process management
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-management-console:1.5.0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-task-console
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Task Console
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '1.5.0'
          annotations:
            description: Runtime image for the Kogito Task Console
            iconClass: icon-jbpm
            tags: kogito,task-console
            supports: business process management
            version: '1.5.0'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-task-console:1.5.0
