services:
  infinispan:
    image: infinispan/server:13.0.2.Final
    container_name: infinispan
    ports:
      - "11222:11222"
    command: "-c infinispan-demo.xml"
    volumes:
      - ./infinispan/infinispan.xml:/opt/infinispan/server/conf/infinispan-demo.xml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11222/rest/v2/cache-managers/default/health/status" ]
      interval: 1s
      timeout: 1s
      retries: 50

  jobs-service-all-in-one:
    image: quay.io/kiegroup/kogito-jobs-service-allinone:latest
    container_name: jobs-service
    ports:
      - "8080:8080"
    depends_on:
      infinispan:
        condition: service_healthy
    environment:
      JOBS_SERVICE_PERSISTENCE: infinispan
      KOGITO_JOBS_SERVICE_KNATIVE_EVENTS: "false"
      QUARKUS_INFINISPAN_CLIENT_SERVER_LIST: infinispan:11222
      QUARKUS_INFINISPAN_CLIENT_USE_AUTH: "false"