services:
  postgres:
    image: postgres:13.4-alpine3.14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "kogito", "-U", "kogito-user" ]
      timeout: 45s
      interval: 10s
      retries: 50
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  jobs-service-all-in-one:
    image: quay.io/kiegroup/kogito-jobs-service-allinone:latest
    container_name: jobs-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      JOBS_SERVICE_PERSISTENCE: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/kogito"
      QUARKUS_DATASOURCE_USERNAME: kogito-user
      QUARKUS_DATASOURCE_PASSWORD: kogito-pass
      KOGITO_JOBS_SERVICE_KNATIVE_EVENTS: "false"