name: Run S2I modules Bats Tests
  
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh $HOME
      - name: run data index tests
        working-directory: ${{ github.workspace }}
        run: |
          ls -la .
          $HOME/bin/bats s2i/modules/kogito-data-index/tests/bats


